import type { ISelectItem } from '~/types/ISelectItem';

export const provinces: ISelectItem[] = [
  { label: 'آذربایجان شرقی', value: 1 },
  { label: 'آذربایجان غربی', value: 2 },
  { label: 'اردبیل', value: 3 },
  { label: 'اصفهان', value: 4 },
  { label: 'البرز', value: 5 },
  { label: 'ایلام', value: 6 },
  { label: 'بوشهر', value: 7 },
  { label: 'تهران', value: 8 },
  { label: 'چهارمحال بختیاری', value: 9 },
  { label: 'خراسان جنوبی', value: 10 },
  { label: 'خراسان رضوی', value: 11 },
  { label: 'خراسان شمالی', value: 12 },
  { label: 'خوزستان', value: 13 },
  { label: 'زنجان', value: 14 },
  { label: 'سمنان', value: 15 },
  { label: 'سیستان و بلوچستان', value: 16 },
  { label: 'فارس', value: 17 },
  { label: 'قزوین', value: 18 },
  { label: 'قم', value: 19 },
  { label: 'کردستان', value: 20 },
  { label: 'کرمان', value: 21 },
  { label: 'کرمانشاه', value: 22 },
  { label: 'کهكيلويه و بويراحمد', value: 23 },
  { label: 'گلستان', value: 24 },
  { label: 'گیلان', value: 25 },
  { label: 'لرستان', value: 26 },
  { label: 'مازندران', value: 27 },
  { label: 'مرکزی', value: 28 },
  { label: 'هرمزگان', value: 29 },
  { label: 'همدان', value: 30 },
  { label: 'یزد', value: 31 },
];